echo '👋 Welcome to the Phoenix LiveView Tutorial Codespace!'
echo '  - Setup the application by running: `mix setup`'
echo '  - When that is finished run: `mix phx.server`'
echo ''
echo 'Then if you then browse to http: //localhost:4000 you should see a list of the LiveView projects we'll build. They won't do anything interesting just yet. 😉'
echo ''
echo '🔍 To explore VS Code to its fullest, search using the Command Palette (Cmd/Ctrl + Shift + P or F1).'
echo ''
echo '📝 Edit away, run your app as usual, and we''ll automatically make it available for you to access.'
echo ''
echo 'Follow along at https: //online.pragmaticstudio.com/tour/courses/liveview-2ed-pro/start'
